### ISSUE TITLE
About NIQE

### ISSUE THREAD

**Issue by 33KU** [zhaozunjin/RetinexDIP#1]
Hi, it's a good job. May I ask how to calculate NIQE？

**Comment by zhaozunjin** [comment]
>

**Comment by zhaozunjin** [comment]
> Hi, it's a good job. May I ask how to calculate NIQE？

You may refer to https://github.com/utlive/niqe. Actually NIQE can be used in [matlab ](https://www.mathworks.com/help/images/ref/niqe.html)and also in python Pakage [scikit-video](http://www.scikit-video.org/stable/modules/generated/skvideo.measure.niqe.html).
